/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Classes.JanelaPrincipal;
import Classes.Login;
import Janelas.Alteracao;
import Classes.ProdutoCRUD;

/**
 *
 * @author convidado
 */
public class CadastroProdutos extends javax.swing.JFrame {

   Inclusao inclusao;
   Alteracao alteracao;
   Excluir exclusao;
   Consulta consulta;
    
    public CadastroProdutos() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(Login.DISPOSE_ON_CLOSE);
        //setExtendedState(JanelaPrincipal.MAXIMIZED_BOTH); 
    }

    CadastroProdutos(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnInclusao = new javax.swing.JButton();
        btnAlteracao = new javax.swing.JButton();
        btnExclusao = new javax.swing.JButton();
        btnSelecao = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInclusao.setText("INCLUSÃO");
        btnInclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInclusaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInclusao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 100, -1));

        btnAlteracao.setText("ALTERAÇÃO");
        btnAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteracaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlteracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        btnExclusao.setText("EXCLUSÃO");
        btnExclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExclusaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnExclusao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 100, -1));

        btnSelecao.setText("SELEÇÃO");
        btnSelecao.setToolTipText("");
        btnSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 100, -1));

        btnConsulta.setText("CONSULTA");
        btnConsulta.setToolTipText("");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CADASTRO (1).png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecaoActionPerformed
        //selecao = new Selecao();
        //selecao.setLocationRelativeTo(null);
        //selecao.setVisible(true);
        
    }//GEN-LAST:event_btnSelecaoActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        consulta = new Consulta();
        consulta.setLocationRelativeTo(null);
        consulta.setVisible(true);    
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnInclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInclusaoActionPerformed
        inclusao = new Inclusao();
        inclusao.setLocationRelativeTo(null);
        inclusao.setVisible(true);                                    
    }//GEN-LAST:event_btnInclusaoActionPerformed

    private void btnExclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExclusaoActionPerformed
        exclusao = new Excluir();
        exclusao.setLocationRelativeTo(null);
        exclusao.setVisible(true); 
    }//GEN-LAST:event_btnExclusaoActionPerformed

    
    private void btnAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteracaoActionPerformed
        alteracao = new Alteracao();
        alteracao.setLocationRelativeTo(null);
        alteracao.setVisible(true); 
    }//GEN-LAST:event_btnAlteracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlteracao;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnExclusao;
    private javax.swing.JButton btnInclusao;
    private javax.swing.JButton btnSelecao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
